config/routes.rb
Rails.application.routes.draw do

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  root 'welcome#index'

  get '/landing' => 'welcome#index'
  get '/about' => 'welcome#about'

  get '/approve' => 'welcome#approve'
  get '/deny' => 'welcome#deny'

  post "/friends/unfollow" => "friends#unfollow", :as => :unfollow
  post "/friends/follow" => "friends#follow", :as => :follow

  post "/friends/congratulate" => "friends#congratulate", :as => :congratulate
  post "/friends/warn" => "friends#warn", :as => :warn

  get '/friends/:id', to: 'friends#show', as: 'friend'

  post "/welcome/description" => "welcome#description", :as => :description

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController


  def unfollow
    p params

    create_client

    @@client.unfollow(params["screen_name"])
    render json: 'Successfully unfollowed.'
  end

  def follow
    p params

    create_client

    @@client.follow(params['screen_name'])
    render json: 'Successfully followed.'
  end

  def congratulate
    create_client
    user_name = params['screen_name']

    @@client.update("You've passed my judgement, @"+user_name+": http://betterfeed.com/tweetjudge")
    render json: 'Successfully congratulated.'
  end

  def warn
    create_client
    user_name = params['screen_name']

    @@client.update("You've failed to pass my judgement, @"+user_name+": http://betterfeed.com/tweetjudge")
    render json: 'Successfully warned.'
  end

  def show
    @friend = params[:id]
    @description = session[:description]

    create_client

    # Get friend object
    @friend_object = @@client.user(@friend)

    # @friend_tweets = @@client.user(:id).home_timeline
    @friend_tweets = []

    # store 100 tweets in a temp array
    @temp_tweets = @@client.user_timeline(@friend, :count => 200)#.take(10000)
    p @temp_tweets
    # roll through each one of the temp tweets...
    @temp_tweets.each do |temp_tweet|
      p temp_tweet
      # determining if it starts with @
      if temp_tweet.text[0] != "@"
        # if it doesn't add it to @friend_tweets
        @friend_tweets << temp_tweet
      end
    end

    @friend_tweets = @friend_tweets.take(30)
    # if it gets through the entire array and @friend_tweets doesn't hit the limit, we add more tweets to the temp_array, and keep going through until this is done
  end


  private

  def create_client
    @@client = Twitter::REST::Client.new do |config|
      config.consumer_key        = 'LBGnh2YckjElEXK5d5SKgQwjd'
      config.consumer_secret     = '5bJuP61h4Ceg5cZHoNGMrDDn2TjMlCMlf60gfg58ktWyyWhsC0'
      config.access_token        = session['access_token']
      config.access_token_secret = session['access_token_secret']
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    # auth.each do |auth_item|
    #   p auth_item
    #   p
    # end

    # Find or Create the User
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)

    # Storing important info in the session
    session[:user_id] = user.id
    session[:access_token] = request.env['omniauth.auth']['credentials']['token']
    session[:access_token_secret] = request.env['omniauth.auth']['credentials']['secret']
    session[:description] = ""

    # Redirecting back to the root
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action

  def index
    @description = session[:description]
    if current_user
      create_client
      @friends = @@client.friends
    end
  end

  def description
    session[:description] = params[:description]

    redirect_to root_path
  end

  private

  def create_client
    @@client = Twitter::REST::Client.new do |config|
      config.consumer_key        = 'LBGnh2YckjElEXK5d5SKgQwjd'
      config.consumer_secret     = '5bJuP61h4Ceg5cZHoNGMrDDn2TjMlCMlf60gfg58ktWyyWhsC0'
      config.access_token        = session['access_token']
      config.access_token_secret = session['access_token_secret']
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/views/friends/show.html.erb
<div class="base-container"><div class="inner-container">Let's review @<%= @friend %>'s twenty latest tweets:</div></div>

<div ng-controller="JudgeController">

  <table><tr>
  <!-- User Info -->
  <td>
  <div style="border-radius: 10px; width:260px; display: inline-block; vertical-align: text-top; margin: 4px; background-color: #FFFFFF; box-shadow: 0px 2px 0px #888888">
    <table>
      <tr style="margin-top: 10px;">
        <td width="10%" style="padding-top: 10px;">
        <!-- Image -->
        <div class="profile-figure">
        <%= image_tag(@friend_object.profile_image_uri) %>
        </div>
        </td>
        <!-- Handle and Name -->
        <td width="90%" colspan="2" style="padding-top: 10px;">
          <div class="header-figure" style="background: url(<%=@friend_object.profile_banner_uri%>);">
          <strong style="background-color: White;"><%= link_to "#{@friend_object.name}", friend_path(@friend_object.screen_name), class: "user-header" %></strong>
          <br>
          <%= link_to "@#{@friend_object.screen_name}", friend_path(@friend_object.screen_name), class: "user-header" %>
          </div>
        </td>
      </tr>
      <!-- Description -->
      <tr>
        <td colspan="3"><%= auto_link(@friend_object.description) %></td>
      </tr>
      <!-- Followers, Following, Tweets -->
      <tr>
        <td style="text-align: center;"><strong>Tweets</strong><br><%= @friend_object.tweets_count %></td>
        <td style="text-align: center;"><strong>Followers</strong><br><%= @friend_object.followers_count %></td>
        <td style="text-align: center;"><strong>Following</strong><br><%= @friend_object.friends_count %></td>
      </tr>
    </table>
  </div>
  </td>
  <!-- Tweet Description -->
  <td width="90%">
  <div class="base-container"><div class="inner-container">
    <span style="font-size: 24px;">This is what you want out of your tweets</span><br>
    <span style=""><%= @description %></span>
  </div></div>
  </td>
  </tr></table>

  <!-- Listing Tweets To Vote On -->
  <div class="base-container"><div class="inner-container">Judge these 30 Tweets!</div></div>
  <div style="border-radius: 10px; text-align: center; background-color: #444;">
  <%= content_tag "div", id: "products", data: {products: @friend_tweets} do %>
    <div ng-repeat="tweet in tweets" style="margin: 4px; padding: 4px; border-radius: 5px;">
      <div class="base-container">
      <table><tr>
      <!-- Tweet Number -->
      <td style="width: 32px;"><span style="padding: 4px; font-size: 16px; background-color: #ff7f00; color: white; border-radius: 20px;">{{$index+1}}</span></td>
      <!-- Tweet Vote Up -->
      <td style="width: 48px;"><span ng-class="getUpClass($index)" ng-click="voteUp($index)"><span class="glyphicon glyphicon-thumbs-up" style="font-size: 32px; padding: 4px;"></span></span></td>
      <!-- Tweet Vote Down -->
      <td style="width: 48px;"><span ng-class="getDownClass($index)" ng-click="voteDown($index)"><span class="glyphicon glyphicon-thumbs-down" style="font-size: 32px; padding: 4px;"></span></span></td>
      <!-- Tweet Text -->
      <td><div class="inner-container"><span style="padding: 4px;"><a ng-href="https://twitter.com/{{tweet.user.screen_name}}/status/{{tweet.id_str}}" target="_blank">
        {{tweet.text}}</a></span></div>
        <div class="inner-container" style="background-color: #ff7f00;"><span class="glyphicon glyphicon-star" style="font-size: 16px; color: white;"> {{tweet.favorite_count}}</span>
        <span class="glyphicon glyphicon-retweet" style="font-size: 16px; color: white;"> {{tweet.retweet_count}}</span></div></td>
      </tr></table></div>
    </div>
  <% end %>
  </div>

  <!-- Results depending on tweets rated and total score -->

  <div class="base-container">
  <div ng-if="total < 30">
    <h4 style="margin: 4px; padding: 4px; border-radius: 5px; background-color: White; text-align: center;">
      You have rated {{total}} of <%= @friend_tweets.size %> tweets. Rate all the tweets above to see your results!
    </h4>
  </div>
  <div ng-if="total == 30">
    <div ng-if="score < 15">
      <table>
      <tr>
        <td colspan="2">
        <div class="inner-container"><h4 style="text-align: center;">Uh oh! <strong>@<%= @friend %></strong> has not passed your judgement. Either give them some advice about what you'd love to see them tweet more about, or unfollow them to clean up your feed.</h4></div>
        </td>
      </tr>
      <tr>
        <td width="50%"><div class="inner-container" style="text-align: center;">
        <h5 style="text-align: center;">Give <strong>@<%= @friend %></strong> a <a href="https://vimeo.com/76762772">kind, actionable, specific recommendation</a> to improve their tweets.</h5>
        <!-- Warn Tweet Button -->
        <form class='follow-button' data-remote='true' action='/friends/warn' method= 'post'>
          <input name='screen_name' type='hidden' value=<%=@friend.to_s%>>
          <input name='original_referer' type='hidden' value='http://platform.twitter.com/widgets/follow_button.df71e9fd75415d2cee8cfded99ebe79f.en.html'>
          <input class='twitter-follow-button' type='submit' value=<%= "warn @"+@friend %>>
        </form>
        </div></td>
        <td width="50%"><div class="inner-container" style="text-align: center;">
        <h5 style="text-align: center;">Unfollow <strong>@<%= @friend %></strong> and un-clutter your feed.</h5>
        <!-- Unfollow Button -->
        <form class='follow-button' data-remote='true' action='/friends/unfollow' method= 'post'>
          <input name='screen_name' type='hidden' value=<%=@friend.to_s%>>
          <input name='original_referer' type='hidden' value='http://platform.twitter.com/widgets/follow_button.df71e9fd75415d2cee8cfded99ebe79f.en.html'>
          <input class='twitter-follow-button' type='submit' value=<%= "unfollow @"+@friend %>>
        </form>
        </div></td>
      </tr>
      </table>
    </div>
    <div ng-if="score >= 15">
      <h4 style="background: LightGray; margin: 4px; padding: 4px; border-radius: 5px;">
        @<%= @friend %> has passed your judgement!
        <!-- You passed tweet button -->
        <form class='follow-button' data-remote='true' action='/friends/congratulate' method= 'post'>
          <input name='screen_name' type='hidden' value=<%=@friend.to_s%>>
          <input name='original_referer' type='hidden' value='http://platform.twitter.com/widgets/follow_button.df71e9fd75415d2cee8cfded99ebe79f.en.html'>
          <input class='twitter-follow-button' type='submit' value=<%= "congratulate @"+@friend %>>
        </form>
      </h4>
    </div>
  </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>BetterFeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- CSS -->


  <!-- JS -->
  <!-- load angular, nganimate, and ui-router -->
  <script src= "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.10/angular-ui-router.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular-animate.min.js"></script>
  <script src="app.js"></script>
  <!-- Mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">

</head>
<body>

<div class="container-fluid">
<!-- Header -->
<div class="row-fluid">
  <div class="span12">
  <%= nav_bar brand: "abetterfeed", fixed: :top, responsive: true do %>
    <%= menu_group do %>
      <%= menu_item "Home", root_path %>
      <%= menu_item "About", '/about' %>
    <% end %>
    <% if current_user %>
      <%= menu_group pull: :right do %>
        <%= menu_item "Log Out", signout_path %>
      <% end %>
    <% else %>
      <%= menu_group pull: :right do %>
        <%= menu_item "Sign in with Twitter", "/auth/twitter" %>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

<!-- Body -->
<div ng-app="myApp">
<div ng-controller="MainController">
  <div class="row-fluid" style="margin-top: 64px;">
      <div class="span9"><%= yield %></div>
  </div>
</div>
</div>


<!-- Footer -->
</div>

</body>
</html>

app/views/welcome/_criteria_introduction.html.erb
<div class="base-container"><div class="inner-container">
  <span style="font-size: 32px;">Welcome to <strong>TweetJudge</strong>!</span>
  <br>
  <span style="font-size: 32px;">Before we start judging tweets, let’s set down some rules for what makes a tweet valuable.</span>
  <br>
  <form class='follow-button' data-remote='true' action='/welcome/description' method= 'post'>
    <input name='description' type='text' value=<%=@description%>>
    <input class='twitter-follow-button' type='submit' value='Update Value!'>
  </form>
</div></div>
<div class="base-container"><div class="inner-container" style="font-size: 24px;">
  <%= @description %>
</div></div>

app/views/welcome/_friend_list.html.erb
<!-- Introduction After Sign In -->
  <div class="base-container"><div class="inner-container">Welcome <%= current_user.name %>!<br><br>Here's a list of twenty people you follow on Twitter. Who would you like to judge first?</div></div>
  <!-- Twitter Friends -->
  <div style="border-radius: 10px; text-align: center; background-color: #444;">
    <% @friends.take(20).each do |friend| %>
      <div style="border-radius: 10px; width:260px; height: 300px; display: inline-block; vertical-align: text-top; margin: 4px; background-color: #279CFF; box-shadow: 0px 2px 0px #888888">
        <table>
          <tr style="margin-top: 10px;">
            <td width="10%" style="padding-top: 10px;">
            <!-- Image -->
            <div class="inner-container" style="width: 52px;">
            <div class="profile-figure">
            <%= image_tag(friend.profile_image_uri) %>
            </div>
            </div>
            </td>
            <!-- Handle and Name -->
            <td width="90%" colspan="2" style="padding-top: 10px;">
              <div class="inner-container">
              <strong style="background-color: White;"><%= link_to "#{friend.name}", friend_path(friend.screen_name), class: "user-header" %></strong>
              <br>
              <%= link_to "@#{friend.screen_name}", friend_path(friend.screen_name), class: "user-header" %>
              </div>
            </td>
          </tr>
          <!-- Description -->
          <tr>
            <td colspan="3"><div class="inner-container"><%= auto_link(friend.description) %></div></td>
          </tr>
          <!-- Followers, Following, Tweets -->
          <tr>
            <td style="text-align: center;"><div class="inner-container"><strong>Tweets</strong><br><%= friend.tweets_count %></div></td>
            <td style="text-align: center;"><div class="inner-container"><strong>Followers</strong><br><%= friend.followers_count %></div></td>
            <td style="text-align: center;"><div class="inner-container"><strong>Following</strong><br><%= friend.friends_count %></div></td>
          </tr>
          <!-- Judge Button -->
          <tr>
            <td colspan="3" style="text-align: center;"><div style="margin: 4px; padding: 4px;">
              <%= button_to "Judge!", friend_path(friend.screen_name), :method => :get, :class => 'judge-button' %>
            </div></td>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
  <br>

app/views/welcome/_landing_tweetjudge.html.erb
<% if current_user %>

<% else %>
  <div>Your Twitter timeline is a chronological stack of tweets from everyone you follow. When you follow lots of interesting, diverse people on Twitter, it's a great way to stay informed.<br>
  Unfortunately, reading your timeline doesn't give you a good sense of the value any single account is providing. Twitter is felt in aggregate, the experience crafted by many people at once.<br>
  When you sign into <strong>betterfeed</strong> with Twitter, you'll be able to assess accounts individually. View their tweets, determine if they're meaningful to you, and then remove them if they're filling up your timeline with junk.</div>
<% end %>

app/views/welcome/about.html.erb
<div class="base-container"><div class="inner-container"><h1>About Betterfeed</h1></div></div>
<div class="base-container"><div class="inner-container"><p><strong>Betterfeed</strong> is a collection of tools to help make your online experience more entertaining, edifying, and uplifting.</p>
<p><strong>Betterfeed</strong> comes from two sources of inspiration: Chicago's strong civic hacking community, and my everyday frustration with popular technology. Let me explain:</p>
<ol>
  <li><strong>Civic Hacking:</strong> Civic hacking is the process of building tools to make government more efficient. Governments will often make their vast data holds available to developers, enabling them to build these tools.</li>
  <li><strong>Popular technology:</strong> The reality is, more people check Facebook than ride public transit. Companies in the private sector are responsible for ubiquitous, essential services. If platforms like Facebook, Twitter, and Google become entirely responsible for our access to information, we should engage in the same level of activism traditionally reserved for public sphere conversations.</li>
</ol>
<p>The Internet is, without question, the most powerful technology available to those who have access. And for most people, the Internet is mediated entirely through major social networks, like Facebook and Twitter.</p>
<p>Some have argued that, because these networks play such an integral role in daily life, they should be public goods. Until that time, I want to build tools that improve the experience of these platforms.</p></div></div>

<div class="base-container"><div class="inner-container"><h2>About TweetJudge</h2></div></div>
<div class="base-container"><div class="inner-container"><p>The Internet is a great place to have opinions, and many websites encourage you to develop and share them with others.</p>
<p>Having opinions is super important! Unfortunately, their ability to be shared isn't what makes them valuable to you, and most websites don't get that.</p></div></div>

<div class="base-container"><div class="inner-container"><h2>About Me</h2></div></div>
<div class="base-container"><div class="inner-container"><p>This site was built by me, DJ DeWitt. I'm a junior web developer based in Chicago, currently looking for freelance or full-time employment opportunities.</p></div></div>

app/views/welcome/index.html.erb
<% if current_user %>
  <% if @description == "" %>
    <%= render 'criteria_introduction' %>
  <% else %>
    <div class="base-container"><div class="inner-container" style="font-size: 24px;"><%= @description %>
    </div></div>
    <%= render 'friend_list' %>
  <% end %>
<% else %>
  <div class="base-container" style="background-color: #ff7f00;"><div class="inner-container" style="font-size: 32px; background-color: #ff7f00; color: white;">
    Welcome to <strong>abetterfeed</strong>
    <br>
    <span style="font-size: 16px;">A family of tools to improve your Internet experience.</span>
  </div></div>
  <div style="border-radius: 10px; text-align: center; background-color: #444;">

    <div style="border-radius: 10px; width:260px; height: 300px; display: inline-block; vertical-align: text-top; margin: 4px; background-color: #279CFF; box-shadow: 0px 2px 0px #888888">
      <table>
        <tr><td><div class="inner-container">
          <span class="glyphicon glyphicon-user" style="font-size: 64px; padding: 4px; color: blue;"></span>
        </div></td></tr>
        <tr><td><div style="color: white; font-size: 32px; margin: 8px;">TweetWizard</div></td></tr>
        <tr><td><div class="inner-container">Find the right people to follow on Twitter, and help others do the same.</div></td></tr>
        <tr><td><div style="margin: 4px; padding: 4px;">
              <%= button_to "Learn More", root_path, :method => :get, :class => 'judge-button' %>
            </div></td></tr>
      </table>
    </div>

    <div style="border-radius: 10px; width:260px; height: 300px; display: inline-block; vertical-align: text-top; margin: 4px; background-color: #279CFF; box-shadow: 0px 2px 0px #888888">
      <table>
        <tr><td><div class="inner-container">
          <span class="glyphicon glyphicon-ok-circle" style="font-size: 64px; padding: 4px; color: blue;"></span>
        </div></td></tr>
        <tr><td><div style="color: white; font-size: 32px; margin: 8px;">TweetJudge</div></td></tr>
        <tr><td><div class="inner-container">Think critically about the people you follow, their tweets, and what you want out of Twitter.</div></td></tr>
        <tr><td><div style="margin: 4px; padding: 4px;">
              <%= button_to "Learn More", root_path, :method => :get, :class => 'judge-button' %>
            </div></td></tr>
      </table>
    </div>

    <div style="border-radius: 10px; width:260px; height: 300px; display: inline-block; vertical-align: text-top; margin: 4px; background-color: #279CFF; box-shadow: 0px 2px 0px #888888">
      <table>
        <tr><td><div class="inner-container">
          <span class="glyphicon glyphicon-tree-conifer" style="font-size: 64px; padding: 4px; color: blue;"></span>
        </div></td></tr>
        <tr><td><div style="color: white; font-size: 32px; margin: 8px;">TweetGuide</div></td></tr>
        <tr><td><div class="inner-container">Learn tips and tricks for making the Internet a kinder, more meaningful place.</div></td></tr>
        <tr><td><div style="margin: 4px; padding: 4px;">
              <%= button_to "Learn More", root_path, :method => :get, :class => 'judge-button' %>
            </div></td></tr>
      </table>
    </div>

  </div>
  <div class="base-container" style="background-color: #ff7f00;"><div class="inner-container" style="font-size: 32px; background-color: #ff7f00; color: white;">
    Why so Twitter?
    <br>
    <span style="font-size: 16px;">If the Internet was created to democratize communication, connection, and information-sharing, Twitter is the closest website to making good on that promise. Having limited time, I wanted to focus on a platform that I care about and can make an impact with. That said, <strong>abetterfeed</strong> will continue to work to become platform agnostic and provide tools for all Internet users.</span>
  </div></div>
  <div class="base-container">
  <div class="twitter-sign-in"><%= link_to "Sign in with Twitter to get started!", "/auth/twitter" %></div>
  </div>
<% end %>